Fixing init script and adding dynamic variable override

diff --git a/templates/default/etc/init.d/knotx.erb b/templates/default/etc/init.d/knotx.erb
--- a/templates/default/etc/init.d/knotx.erb
+++ b/templates/default/etc/init.d/knotx.erb
@@ -17,7 +17,6 @@
 
 . /etc/rc.d/init.d/functions
 
-DAEMON="node"
 LOCK_FILE="/var/lock/subsys/<%= @knotx_id %>"
 JAR_FILE="<%= @knotx_root_dir %>/knotx.jar"
 
@@ -25,17 +24,20 @@ CONFIG_FILE="<%= @knotx_root_dir %>/knotx.conf"
 
 [ -e $CONFIG_FILE ] && . $CONFIG_FILE
 
+# Removing endlines from variable for loading
+STARTUP_OPTS=$(echo $STARTUP_OPTS|tr -d '\n')
+
 do_start()
 {
   if [ ! -f "$LOCK_FILE" ] ; then
     echo -n $"Starting <%= @knotx_id %>: "
-    runuser -l "<%= @knotx_user %>" -c "java -jar $JAR_FILE $JAVA_OPTS 2>&1 >> <%= @knotx_log_dir %>/<%= @knotx_id %>.log &" && echo_success || echo_failure
+    runuser -l "<%= @knotx_user %>" -c "java -jar $JAR_FILE $STARTUP_OPTS >> <%= @knotx_log_dir %>/<%= @knotx_id %>.log 2>&1 &" && echo_success || echo_failure
     RETVAL=$?
     echo
     if [ $RETVAL -eq 0 ] ; then
       touch $LOCK_FILE
     else
-      echo "Error while starting <%= @knotx_id %>. Error code from nodejs: [$RETVAL]"
+      echo "Error while starting <%= @knotx_id %>. Error code from java: [$RETVAL]"
     fi
   else
     echo "<%= @knotx_id %> is locked. Lock file [$LOCK_FILE] is present therefore instance is probably running."
