Updating default knotx version, config and the way the app is started

diff --git a/templates/default/etc/init.d/knotx.erb b/templates/default/etc/init.d/knotx.erb
--- a/templates/default/etc/init.d/knotx.erb
+++ b/templates/default/etc/init.d/knotx.erb
@@ -18,7 +18,7 @@
 . /etc/rc.d/init.d/functions
 
 LOCK_FILE="/var/lock/subsys/<%= @knotx_id %>"
-JAR_FILE="<%= @knotx_root_dir %>/knotx.jar"
+JAR_DIR="<%= @knotx_root_dir %>/app/*"
 
 CONFIG_FILE="<%= @knotx_root_dir %>/knotx.conf"
 
@@ -32,7 +32,7 @@ do_start()
 {
   if [ ! -f "$LOCK_FILE" ] ; then
     echo -n $"Starting <%= @knotx_id %>: "
-    runuser -l "<%= @knotx_user %>" -c "java $KNOTX_OPTS -jar $JAR_FILE $KNOTX_CONFIG $KNOTX_CONFIG_EXTRA >> <%= @knotx_log_dir %>/<%= @knotx_id %>.log 2>&1 &" && echo_success || echo_failure
+    runuser -l "<%= @knotx_user %>" -c "java $KNOTX_OPTS -cp $JAR_DIR com.cognifide.knotx.launcher.LogbackLauncher $KNOTX_CONFIG $KNOTX_CONFIG_EXTRA >> <%= @knotx_log_dir %>/<%= @knotx_id %>.log 2>&1 &" && echo_success || echo_failure
     RETVAL=$?
     echo
     if [ $RETVAL -eq 0 ] ; then
