Redirect knot.x start stdout to a separate log file

diff --git a/templates/default/etc/init.d/knotx.erb b/templates/default/etc/init.d/knotx.erb
--- a/templates/default/etc/init.d/knotx.erb
+++ b/templates/default/etc/init.d/knotx.erb
@@ -40,7 +40,8 @@ start()
   -Dvertx.cli.usage.prefix=knotx \
   -classpath ':<%= @conf_dir %>:<%= ::File.join(@lib_dir, '*') %>' \
   $KNOTX_EXTRA_OPTS \
-  io.vertx.core.Launcher run-knotx >> /dev/null 2>&1 &" && echo_success || echo_failure
+  io.vertx.core.Launcher run-knotx \
+  >> <%= ::File.join(@log_dir, 'start.log') %> 2>&1 &" && echo_success || echo_failure
   RETVAL=$?
   echo
   if [ $RETVAL -ne 0 ] ; then
