Removing lockfiles, removing config generation, simplifying base configuration deployment

diff --git a/templates/default/etc/init.d/knotx.erb b/templates/default/etc/init.d/knotx.erb
--- a/templates/default/etc/init.d/knotx.erb
+++ b/templates/default/etc/init.d/knotx.erb
@@ -17,7 +17,6 @@
 
 . /etc/rc.d/init.d/functions
 
-LOCK_FILE="/var/lock/subsys/<%= @knotx_id %>"
 ROOT_DIR="<%= @knotx_root_dir %>"
 
 CONFIG_FILE="<%= @knotx_root_dir %>/knotx.conf"
@@ -28,40 +27,58 @@ CONFIG_FILE="<%= @knotx_root_dir %>/knotx.conf"
 KNOTX_OPTS=$(echo $KNOTX_OPTS|tr -d '\n')
 KNOTX_CONFIG=$(echo $KNOTX_CONFIG|tr -d '\n')
 
-do_start()
+start()
 {
-  if [ ! -f "$LOCK_FILE" ] ; then
-    echo -n $"Starting <%= @knotx_id %>: "
-    runuser -l "<%= @knotx_user %>" -c "java $KNOTX_OPTS -cp $ROOT_DIR/app/\* com.cognifide.knotx.launcher.LogbackLauncher $KNOTX_CONFIG $KNOTX_CONFIG_EXTRA >> <%= @knotx_log_dir %>/<%= @knotx_id %>.log 2>&1 &" && echo_success || echo_failure
-    RETVAL=$?
-    echo
-    if [ $RETVAL -eq 0 ] ; then
-      touch $LOCK_FILE
-    else
-      echo "Error while starting <%= @knotx_id %>. Error code from java: [$RETVAL]"
-    fi
-  else
-    echo "<%= @knotx_id %> is locked. Lock file [$LOCK_FILE] is present therefore instance is probably running."
-    RETVAL=0
-  fi
-}
-do_stop()
-{
-  echo -n $"Stopping <%= @knotx_id %>: "
-  pid=`ps -aefw | grep "cp $ROOT_DIR/" | grep -v " grep " | awk '{print $2}'`
-  kill -9 $pid > /dev/null 2>&1 && echo_success || echo_failure
+  echo -n $"Starting <%= @knotx_id %>: "
+  runuser -l "<%= @knotx_user %>" -c "java $KNOTX_OPTS -cp $ROOT_DIR/app/\* io.knotx.launcher.LogbackLauncher $KNOTX_CONFIG $KNOTX_CONFIG_EXTRA >> <%= @knotx_log_dir %>/<%= @knotx_id %>.log 2>&1 &" && echo_success || echo_failure
   RETVAL=$?
   echo
-  [ $RETVAL -eq 0 ] && rm -f $LOCK_FILE
+  if [ $RETVAL -ne 0 ] ; then
+    echo "Error while starting <%= @knotx_id %>. Error code from java: [$RETVAL]"
+  fi
 }
+
+get_pid()
+{
+  ps -aefw | grep "cp $ROOT_DIR/" | grep -v " grep " | awk '{print $2}'
+}
+
+do_start()
+{
+  PID=`get_pid`
+  if [ ! -z $PID ] ; then
+    echo "<%= @knotx_id %> is already running"
+    RETVAL=0
+  else
+    start
+  fi
+}
+
+do_stop()
+{
+  PID=`get_pid`
+  if [ ! -z $PID ] ; then
+    echo -n $"Stopping <%= @knotx_id %>: "
+    kill -9 $PID > /dev/null 2>&1 && echo_success || echo_failure
+    RETVAL=$?
+    echo
+    if [ $RETVAL -ne 0 ] ; then
+      echo "<%= @knotx_id %> failed to stop"
+    fi
+  else
+    echo "<%= @knotx_id %> is already stopped"
+  fi
+}
+
 do_status()
 {
-  if [ -f "$LOCK_FILE" ] ; then
-    echo "<%= @knotx_id %> is running..."
-    exit 0
+  PID=`get_pid`
+  if [ ! -z $PID ] ; then
+    echo "<%= @knotx_id %> is running"
+    RETVAL=0
   else
     echo "<%= @knotx_id %> is stopped"
-    exit 3
+    RETVAL=3
   fi
 }
 
