Knotx update, fixing JMX attributes, removing deprecated jxm features

diff --git a/templates/default/etc/init.d/knotx.erb b/templates/default/etc/init.d/knotx.erb
--- a/templates/default/etc/init.d/knotx.erb
+++ b/templates/default/etc/init.d/knotx.erb
@@ -25,13 +25,14 @@ CONFIG_FILE="<%= @knotx_root_dir %>/knotx.conf"
 [ -e $CONFIG_FILE ] && . $CONFIG_FILE
 
 # Removing endlines from variable for loading
-STARTUP_OPTS=$(echo $STARTUP_OPTS|tr -d '\n')
+KNOTX_OPTS=$(echo $KNOTX_OPTS|tr -d '\n')
+KNOTX_CONFIG=$(echo $KNOTX_CONFIG|tr -d '\n')
 
 do_start()
 {
   if [ ! -f "$LOCK_FILE" ] ; then
     echo -n $"Starting <%= @knotx_id %>: "
-    runuser -l "<%= @knotx_user %>" -c "java -jar $JAR_FILE $STARTUP_OPTS >> <%= @knotx_log_dir %>/<%= @knotx_id %>.log 2>&1 &" && echo_success || echo_failure
+    runuser -l "<%= @knotx_user %>" -c "java $KNOTX_OPTS -jar $JAR_FILE $KNOTX_CONFIG >> <%= @knotx_log_dir %>/<%= @knotx_id %>.log 2>&1 &" && echo_success || echo_failure
     RETVAL=$?
     echo
     if [ $RETVAL -eq 0 ] ; then
@@ -47,7 +48,7 @@ do_start()
 do_stop()
 {
   echo -n $"Stopping <%= @knotx_id %>: "
-  pid=`ps -aefw | grep "java -jar $JAR_FILE" | grep -v " grep " | awk '{print $2}'`
+  pid=`ps -aefw | grep "jar $JAR_FILE" | grep -v " grep " | awk '{print $2}'`
   kill -9 $pid > /dev/null 2>&1 && echo_success || echo_failure
   RETVAL=$?
   echo
